version: '3.8'

services:
  db:
    image: postgres:15
    hostname: $POSTGRES_HOST
    ports:
        - $POSTGRES_PORT:5432
    environment:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
        - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  task_api:
    build: ./
    env_file: ./.env
    environment:
      POSTGRES_HOST: db
    container_name: api
    ports:
      - 9999:8000
    restart: always
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


volumes:
  postgres_data:
