version: '3.9'

x-common-env: &common_env
  restart: unless-stopped
  env_file: ./.env
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}

services:
  db:
    image: postgres:15
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    <<: *common_env

  web:
    build: .
    container_name: api
    ports:
      - "9999:8000"
    depends_on:
      db:
        condition: service_healthy
    <<: *common_env

volumes:
  postgres_data:
